### PR TITLE
Adds Observation API usage

### PR DESCRIPTION
**Pull request by marcingrzejszczak**
## Prerequisites

Support for latest Micrometer 2.0.0 snapshots: https://github.com/spring-projects/spring-batch/pull/4060/files

## What's done

- Adds observation for `Job`s and `Step`s. 
- Adds unit tests asserting that proper metrics are being created
- Adds integration test (turns on only when Zipkin is available at a default port) to check how tracing looks like 

### Trace view from Zipkin

image

### Metrics from `MeterRegistry`

Notice the new `spring.batch.job` and `spring.batch.step`.

```
[main] INFO io.micrometer.tracing.test.SampleTestRunner - Gathered the following metrics
	Meter with name <spring.batch.job.active> and type <LONG_TASK_TIMER> has the following measurements 
		<[Measurement{statistic='ACTIVE_TASKS', value=0.0}, Measurement{statistic='DURATION', value=0.0}]> 
		and has the following tags <[tag(name=job)]>
	Meter with name <spring.batch.job> and type <TIMER> has the following measurements 
		<[Measurement{statistic='COUNT', value=1.0}, Measurement{statistic='TOTAL_TIME', value=0.029340031}, Measurement{statistic='MAX', value=0.029340031}]> 
		and has the following tags <[tag(error=none), tag(spring.batch.job.name=job), tag(spring.batch.job.status=COMPLETED)]>
	Meter with name <spring.batch.step> and type <TIMER> has the following measurements 
		<[Measurement{statistic='COUNT', value=1.0}, Measurement{statistic='TOTAL_TIME', value=0.010459161}, Measurement{statistic='MAX', value=0.010459161}]> 
		and has the following tags <[tag(error=none), tag(spring.batch.job.name=job), tag(spring.batch.step.name=step), tag(spring.batch.step.status=COMPLETED)]>
```

cc @jonatan-ivanov @shakuzen

### CODE REVIEW

**Review by jonatan-ivanov — APPROVED** [review]

**Comment by benas** [comment]
Thank you for your effort on this! I'm able to see tracing data in Zipkin in the new sample.

However, the test `org.springframework.batch.sample.metrics.BatchMetricsTests#testBatchMetrics` is failing with this PR even when I add `Metrics.globalRegistry.withTimerObservationHandler();`. Any idea?

**Comment by marcingrzejszczak** [comment]
Yeah, check the commit https://github.com/spring-projects/spring-batch/pull/4065/commits/61ec4d4364447135181c5997c9522634da637957

**Comment by benas** [comment]
Rebased, squashed and merged as e917d75d206816778936c219757c3e80c35af9e9. There are a couple of failing tests that I fixed in ae6c0b9809ad1305715895d8e396a056048c52df.

The documentation changes that are expected to generate metrics and tracing meta-data did not work and failed with the following error:

```
[INFO] --- exec-maven-plugin:3.0.0:java (generate-metrics-metadata) @ spring-batch-docs ---
[WARNING]
java.lang.NoClassDefFoundError: io/micrometer/api/internal/logging/InternalLoggerFactory
    at io.micrometer.docs.metrics.DocsFromSources.<clinit> (DocsFromSources.java:34)
    at jdk.internal.misc.Unsafe.ensureClassInitialized0 (Native Method)
    at jdk.internal.misc.Unsafe.ensureClassInitialized (Unsafe.java:1155)
    at java.lang.invoke.DirectMethodHandle$EnsureInitialized.computeValue (DirectMethodHandle.java:377)
    at java.lang.invoke.DirectMethodHandle$EnsureInitialized.computeValue (DirectMethodHandle.java:374)
    at java.lang.ClassValue.getFromHashMap (ClassValue.java:228)
    at java.lang.ClassValue.getFromBackup (ClassValue.java:210)
    at java.lang.ClassValue.get (ClassValue.java:116)
    at java.lang.invoke.DirectMethodHandle.checkInitialized (DirectMethodHandle.java:400)
    at java.lang.invoke.DirectMethodHandle.ensureInitialized (DirectMethodHandle.java:388)
    at java.lang.invoke.DirectMethodHandle.internalMemberNameEnsureInit (DirectMethodHandle.java:338)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:254)
    at java.lang.Thread.run (Thread.java:833)
Caused by: java.lang.ClassNotFoundException: io.micrometer.api.internal.logging.InternalLoggerFactory
    at java.net.URLClassLoader.findClass (URLClassLoader.java:440)
    at java.lang.ClassLoader.loadClass (ClassLoader.java:587)
    at java.lang.ClassLoader.loadClass (ClassLoader.java:520)
    at io.micrometer.docs.metrics.DocsFromSources.<clinit> (DocsFromSources.java:34)
    at jdk.internal.misc.Unsafe.ensureClassInitialized0 (Native Method)
    at jdk.internal.misc.Unsafe.ensureClassInitialized (Unsafe.java:1155)
    at java.lang.invoke.DirectMethodHandle$EnsureInitialized.computeValue (DirectMethodHandle.java:377)
    at java.lang.invoke.DirectMethodHandle$EnsureInitialized.computeValue (DirectMethodHandle.java:374)
    at java.lang.ClassValue.getFromHashMap (ClassValue.java:228)
    at java.lang.ClassValue.getFromBackup (ClassValue.java:210)
    at java.lang.ClassValue.get (ClassValue.java:116)
    at java.lang.invoke.DirectMethodHandle.checkInitialized (DirectMethodHandle.java:400)
    at java.lang.invoke.DirectMethodHandle.ensureInitialized (DirectMethodHandle.java:388)
    at java.lang.invoke.DirectMethodHandle.internalMemberNameEnsureInit (DirectMethodHandle.java:338)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:254)
    at java.lang.Thread.run (Thread.java:833)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

These changes have been omitted from this PR. Please open a separate PR for that.

Thank you for all your effort in introducing the new Observation APIs in Spring Batch!

**Comment by benas** [comment]
Rebased, squashed and merged as e917d75d206816778936c219757c3e80c35af9e9. There are a couple of failing tests that I fixed in ae6c0b9809ad1305715895d8e396a056048c52df.

The documentation changes that are expected to generate metrics and tracing meta-data did not work and failed with the following error:

```
[INFO] --- exec-maven-plugin:3.0.0:java (generate-metrics-metadata) @ spring-batch-docs ---
[WARNING]
java.lang.NoClassDefFoundError: io/micrometer/api/internal/logging/InternalLoggerFactory
    at io.micrometer.docs.metrics.DocsFromSources.<clinit> (DocsFromSources.java:34)
    at jdk.internal.misc.Unsafe.ensureClassInitialized0 (Native Method)
    at jdk.internal.misc.Unsafe.ensureClassInitialized (Unsafe.java:1155)
    at java.lang.invoke.DirectMethodHandle$EnsureInitialized.computeValue (DirectMethodHandle.java:377)
    at java.lang.invoke.DirectMethodHandle$EnsureInitialized.computeValue (DirectMethodHandle.java:374)
    at java.lang.ClassValue.getFromHashMap (ClassValue.java:228)
    at java.lang.ClassValue.getFromBackup (ClassValue.java:210)
    at java.lang.ClassValue.get (ClassValue.java:116)
    at java.lang.invoke.DirectMethodHandle.checkInitialized (DirectMethodHandle.java:400)
    at java.lang.invoke.DirectMethodHandle.ensureInitialized (DirectMethodHandle.java:388)
    at java.lang.invoke.DirectMethodHandle.internalMemberNameEnsureInit (DirectMethodHandle.java:338)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:254)
    at java.lang.Thread.run (Thread.java:833)
Caused by: java.lang.ClassNotFoundException: io.micrometer.api.internal.logging.InternalLoggerFactory
    at java.net.URLClassLoader.findClass (URLClassLoader.java:440)
    at java.lang.ClassLoader.loadClass (ClassLoader.java:587)
    at java.lang.ClassLoader.loadClass (ClassLoader.java:520)
    at io.micrometer.docs.metrics.DocsFromSources.<clinit> (DocsFromSources.java:34)
    at jdk.internal.misc.Unsafe.ensureClassInitialized0 (Native Method)
    at jdk.internal.misc.Unsafe.ensureClassInitialized (Unsafe.java:1155)
    at java.lang.invoke.DirectMethodHandle$EnsureInitialized.computeValue (DirectMethodHandle.java:377)
    at java.lang.invoke.DirectMethodHandle$EnsureInitialized.computeValue (DirectMethodHandle.java:374)
    at java.lang.ClassValue.getFromHashMap (ClassValue.java:228)
    at java.lang.ClassValue.getFromBackup (ClassValue.java:210)
    at java.lang.ClassValue.get (ClassValue.java:116)
    at java.lang.invoke.DirectMethodHandle.checkInitialized (DirectMethodHandle.java:400)
    at java.lang.invoke.DirectMethodHandle.ensureInitialized (DirectMethodHandle.java:388)
    at java.lang.invoke.DirectMethodHandle.internalMemberNameEnsureInit (DirectMethodHandle.java:338)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:254)
    at java.lang.Thread.run (Thread.java:833)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

These changes have been omitted from this PR. Please open a separate PR for that.

Thank you for all your effort in introducing the new Observation APIs in Spring Batch!
